baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Alex's Portfolio"
theme = "basic"
[params]
    author = "Alex Wohlleber"
    description = "My portfolio site"
    gh_url = "https://api.github.com/users"
    gh_user = "alwoh"